### ISSUE TITLE
Support Restic Rest server as backend.

### ISSUE THREAD

**Issue by tamalsaha** [appscode/stash#126]
If there are enough user request, we should add this.

**Comment by pierreozoux** [comment]
@tamalsaha hey, I'd be interested in that, especially the append-only feature ;)

I'm not a go expert, but if you give me some guidance, I can try to make a PR.

Thanks for your help!

**Comment by tamalsaha** [comment]
@galexrt  started working on it https://github.com/appscode/stash/pull/434 . This will require some underlying changes in stash which are captured in #439 . This a non-trivial change given everything is done currently. So, we need to come up with sort of high level plan and design.

**Comment by fpytloun** [comment]
Yes, it would be great to have this feature. Any update on when it will be released?

**Comment by tamalsaha** [comment]
This will be supported by https://github.com/appscode/stash/issues/648 . We hope to be code complete this month, then write docs and release the rc.

**Comment by tamalsaha** [comment]
Fixed by https://github.com/appscode/stash/pull/713
