### ISSUE TITLE
Collect ideas on how to improve recovery process

### ISSUE THREAD

**Issue by tamalsaha** [appscode/stash#131]
One idea is to create a Recover TPR. If created, we can launch a Job to
- dynamically create a PV
- Recover into the PV using restic.
- Shutdown Job

**Comment by rimusz** [comment]
sounds as a right process

**Comment by tamalsaha** [comment]
Thanks @rimusz ! If we create the new PV dynamically, I think there will be no name collision. Also, users might want to restore in an existing PV.

**Comment by rimusz** [comment]
indeed, in some cases users might want to restore into the existing PV, so data needs to be deleted there and restored from the backup.

**Comment by rimusz** [comment]
what are your plans on restore story, how soon it can be done? 
do you need any help with that?

**Comment by tamalsaha** [comment]
I want to get this done before 3.0.0. I want to reach 3.0.0 by end of this month, so that we can start work on Kube 1.7+.

> do you need any help with that?

Thanks for wanting to help. I really appreciate this. The easiest way to help will be to test this feature and give your feedback on the UX. If want to contribute code, we should talk about the design first.

**Comment by tamalsaha** [comment]
Based on my discussion on our [slack](https://slack.appscode.com/) channel with @m-ferrero :

 - being able to restore into the existing pv seems to me the first thing
at the moment we use bacula and more often than not customers request that kind of restore

- another improvement could be being able to suspend backup during restore, but this could be useful in other conditions too and probably it can be achieved by modifying the tpr

- I think in this kind of architecture there is a problem with open files: if a process is keeping a file open restic won't be able to restore it
in a "normal" environment (no microservices) you would stop services and restore the file
here if you stop processes kubernetes will restart the pods
but it true that if a file is open the backup is not consistent, so probably this problem is not so serious

- but this could be handled by stash: an advanced option could be to set the deployment to 0 replicas, perform the restore an then rescale the deployment

- yes, exactly, but this should be an option (stopping the workload), there could be cases where I want to restore the files in the original PV and the workload can remain running

**Comment by tamalsaha** [comment]
We have released 0.6.0 with Recovery support using CRD. https://appscode.com/products/stash/0.6.0/guides/restore/

Please give it a shot and let us know if you see any issues or have feature requests.
