### ISSUE TITLE
stash Helm chart needs docs to use it with backups to S3/GCS/Azure storage 

### ISSUE THREAD

**Issue by rimusz** [appscode/stash#136]

**Comment by tamalsaha** [comment]
Backends are documented here: https://github.com/appscode/stash/blob/master/docs/backends.md . Is there anything specifically needed for Helm chart?

**Comment by rimusz** [comment]
so backend needs to be installed separately from the helm chart?

**Comment by tamalsaha** [comment]
No. If you follow the tutorial https://github.com/appscode/stash/blob/master/docs/tutorial.md , I used a local emptyDir as a backend for example.

Instead change the `spec.backend` for your Restic tpr to one of the backends and also create the secret accordingly. Then Stash will backup in that backend.

**Comment by tamalsaha** [comment]
Closing this bug. If you are still having trouble, please reopen.
