### ISSUE TITLE
Is it possible for stash/restic to create a point in time snapshot for statefulset?

### ISSUE THREAD

**Issue by tweakmy** [appscode/stash#146]
As per the topic. Is this even practical?

**Comment by tamalsaha** [comment]
This is not possible today. Until Kubernetes supports volume snapshotting, this can't be done, I believe.

**Comment by tamalsaha** [comment]
Dup #4

**Comment by manishg4** [comment]
Just like FlexVolume allows a vendor neutral way of mounting a Storage entity which is provisioned on *ANY* chassis; is there a generic way/ method in K8s to create snapshots / clones run time on third party storage chassis?

I see there is a built in support in K8s for Snapshots; however, this seems integrated only with the Google Cloud services.

Is there a generic method for integrating the K8s Snapshots and Clones features with storage provisioned from a third party array?
