### ISSUE TITLE
[Bug] Success/Fail prometheus metrics inverted condition

### ISSUE THREAD

**Issue by fabiormoura** [appscode/stash#175]
Hi,

I found two of the metrics sent to pushgateway with its boolean values flipped.

See snippet below where it happens:

https://github.com/appscode/stash/blob/e6065cb275eefd915ca4e68ae1a336f6510c091b/pkg/scheduler/scheduler.go#L289-L295

I believe the expected behaviour is having the success metric as 0 and fail as 1 when `err != nil`

**Comment by tamalsaha** [comment]
Thanks @fabiormoura ! It is fixed in master branch now.
