### ISSUE TITLE
invalid header field value for key Authorization - DO s3 bucket

### ISSUE THREAD

**Issue by HerrmannHinz** [appscode/stash#189]
hello,

trying to get stash working against digital ocean's s3 dependance called "spaces". 
see: [https://www.digitalocean.com/community/tutorials/an-introduction-to-digitalocean-spaces](https://www.digitalocean.com/community/tutorials/an-introduction-to-digitalocean-spaces)

i get the following errors: 

`[golang-sh]$ /bin/restic snapshots --json
unable to open config file: Stat: Get https://nyc3.digitaloceanspaces.com/my-bucket/?location=: net/http: invalid header field value "AWS4-HMAC-SHA256 Credential=XXXXXXXXXXXXXXXXXX\n/20171009/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=7613f92164ddc1ca55c2dac169fd5bff55a31673d2bc962f7b3477679586fd80" for key Authorization
Is there a repository at the following location?
s3:nyc3.digitaloceanspaces.com/my-bucket`

`[golang-sh]$ /bin/restic init
create backend at s3:nyc3.digitaloceanspaces.com/my-bucket failed: client.BucketExists: Get https://nyc3.digitaloceanspaces.com/my-bucket/?location=: net/http: invalid header field value "AWS4-HMAC-SHA256 Credential=XXXXXXXXXXXXXXXXXX\n/20171009/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=7613f92164ddc1ca55c2dac169fd5bff55a31673d2bc962f7b3477679586fd80" for key Authorization`

`I1009 11:33:00.034023       1 scheduler.go:207] exit status 1` 

any idea? does anyone of you got this working already? 

for me it seems like that DO spaces is returning some header value which the s3 backend isnt aware of.

**Comment by tamalsaha** [comment]
I tried using the latest restic cli from command line. It seems to work:
```
$ restic -r s3:https://nyc3.digitaloceanspaces.com/restic init
$ restic -r s3:nyc3.digitaloceanspaces.com/restic backup ~/photos
```

**Comment by HerrmannHinz** [comment]
yup. tried it from within the container(appscode/stash:0.5.0-beta.0) of a demo pod
and i can confirm as well, using the /bin/restic (0.7.3) cli - works. 

let me know if and how to test the updated binary. u talking about the stash bin i assume?

**Comment by tamalsaha** [comment]
We are going to cut a release for 0.5.0

**Comment by tamalsaha** [comment]
We have released 0.5.0

**Comment by HerrmannHinz** [comment]
quick note here: 

- we found some issues in the stash code which have been fixed in >0.5.0, right? 
- the restic debug message was a little bit unclear, also turned out that i had bad kubernetes/DO credentials in use when doing the backups.

**Comment by tamalsaha** [comment]
> we found some issues in the stash code which have been fixed in >0.5.0, right?

I believe all issues were addressed by 0.5.1 . If you see new issues, please update here.

**Comment by HerrmannHinz** [comment]
@tamalsaha no i don't - but check this: 
https://github.com/appscode/stash/issues/189

**Comment by tamalsaha** [comment]
Yeah. 0.5.1 was cut after this (Oct 10).
