### ISSUE TITLE
Upgrade procedure for 0.5.1 -> 0.6.0

### ISSUE THREAD

**Issue by tamalsaha** [appscode/stash#237]
- [x] Restic YAML fix
- [x] Repository location
- [x] Update StatefulSet side-cars and restart pods.
- [x] `strings.Lower(workload.Kind)` https://github.com/appscode/stash/blob/2becb354e43573909fb4e80de0186256d6f4d290/apis/stash/v1alpha1/workload.go#L37

**Comment by diptadas** [comment]
If we delete old `Restic` and re-deploy it after moving repository contents to new location, backup count in `Rsetic` status will start from zero again.  Instead we can do following:
- Change `Restic` selector to an invalid one
- Move repository contents to new location
- Update `Restic` selector to previous one
