### ISSUE TITLE
Replace fmt.Print* with log statements

### ISSUE THREAD

**Issue by galexrt** [appscode/stash#248]
It would be good to have better control over the log amount of stash through the `--v=X` flag. This is currently not fully possible for the whole output of the stash operator as there are some points in code where for example `fmt.Printf()` is used and which is then "spamming" the output even though the `--v=0` is set.

Example code lines:
* https://github.com/appscode/stash/blob/7241c6ddfb409d7b8bcffe0ebc4721c18e3c937b/pkg/controller/jobs.go#L108
* https://github.com/appscode/stash/blob/7241c6ddfb409d7b8bcffe0ebc4721c18e3c937b/pkg/backup/restic.go#L137

Would you be taking a PR that changes the `fmt.Printf()`s to `log.LEVELln()` (most likely for most lines to be `INFO` level) statements?

**Comment by tamalsaha** [comment]
Please send a pr :)
