### ISSUE TITLE
Double Deployment patch when deleting a Restic CRD?

### ISSUE THREAD

**Issue by whereisaaron** [appscode/stash#281]
When deleting a Restic CRD pointing to a Deployment, the sidecar is patched out of the Deployment, and this the Pod is re-created. However I noticed the Deployment seems to get patched twice? See below upon deleting the CRD, the Pod was re-created twice in quick succession, the first time still with a sidecar, and the second time without.

Is this two-step process expected/necessary for removing the sidecar?

```
$ kubectl get pod
NAME                         READY     STATUS        RESTARTS   AGE
stash-demo-6444696cb-fvv2c   2/2       Running       0          49m

$ kubectl delete restic stash-demo
restic "stash-demo" deleted

$ kubectl get pod
NAME                         READY     STATUS        RESTARTS   AGE
stash-demo-5c59975fc-dq4t8   1/1       Running       0          3s
stash-demo-6444696cb-fvv2c   2/2       Terminating   0          50m
stash-demo-6444696cb-v9w7b   1/2       Terminating   0          3s

$ kubectl get pod
NAME                         READY     STATUS        RESTARTS   AGE
stash-demo-5c59975fc-dq4t8   1/1       Running       0          33s
stash-demo-6444696cb-fvv2c   0/2       Terminating   0          50m
stash-demo-6444696cb-v9w7b   0/2       Terminating   0          33s

$ kubectl get pod
NAME                         READY     STATUS    RESTARTS   AGE
stash-demo-5c59975fc-dq4t8   1/1       Running   0          2m
```

**Comment by tamalsaha** [comment]
I believe this is happening because of https://github.com/appscode/stash/blob/master/pkg/util/kubernetes.go#L142 .

In old days ( <= 1.6), DaemonSet pods will not restart when it's spec was changed. So, I decided to actively check for pods without sidecar etc and restart them. This causes this behavior,  because we delete the old pod, because the Deployment controller is ready to delete this.

**Comment by tamalsaha** [comment]
We have decided to set the `spec.updateStrategy` to `RollingUpdate` for DaemonSet and StatefulSet. And remove these 2 method calls from all 5 workload types.
