### ISSUE TITLE
Recovery not working!

### ISSUE THREAD

**Issue by xpowerman** [appscode/stash#303]
Hi. I install stash via helm with rbac on kubernetes 1.9. I make restic for deployment.

```
---

apiVersion: stash.appscode.com/v1alpha1
kind: Restic
metadata:
  name: voipmonitor-gui
  namespace: voipmonitor
spec:
  selector:
    matchLabels:
      app: voipmonitor-gui
  fileGroups:
  - path: /var/www
    retentionPolicyName: 'keep-last-5'
  backend:
    local:
      mountPath: /mnt/backup/stash
      hostPath:
        path: /mnt/backup/stash
    storageSecretName: voipmonitor-gui
  schedule: '@every 30m'
  volumeMounts:
  - mountPath: /var/www
    name: voipmonitor-gui-rook
  retentionPolicies:
  - name: 'keep-last-5'
    keepLast: 5
    prune: true

```
Seems that it make backups, because a backup count increased and some files appears in backend.

```
apiVersion: v1
items:
- apiVersion: stash.appscode.com/v1alpha1
  kind: Restic
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"stash.appscode.com/v1alpha1","kind":"Restic","metadata":{"annotations":{},"name":"voipmonitor-gui","namespace":"voipmonitor"},"spec":{"backend":{"local":{"hostPath":{"path":"/mnt/backup/stash"},"mountPath":"/mnt/backup/stash"},"storageSecretName":"voipmonitor-gui"},"fileGroups":[{"path":"/var/www","retentionPolicyName":"keep-last-5"}],"retentionPolicies":[{"keepLast":5,"name":"keep-last-5","prune":true}],"schedule":"@every 30m","selector":{"matchLabels":{"app":"voipmonitor-gui"}},"volumeMounts":[{"mountPath":"/var/www","name":"voipmonitor-gui-rook"}]}}
    clusterName: ""
    creationTimestamp: 2018-01-26T06:33:50Z
    generation: 0
    name: voipmonitor-gui
    namespace: voipmonitor
    resourceVersion: "2052717"
    selfLink: /apis/stash.appscode.com/v1alpha1/namespaces/voipmonitor/restics/voipmonitor-gui
    uid: deacc419-0262-11e8-85c4-d43d7ed6ce3b
  spec:
    backend:
      local:
        hostPath:
          path: /mnt/backup/stash
        mountPath: /mnt/backup/stash
      storageSecretName: voipmonitor-gui
    fileGroups:
    - path: /var/www
      retentionPolicyName: keep-last-5
    retentionPolicies:
    - keepLast: 5
      name: keep-last-5
      prune: true
    schedule: '@every 30m'
    selector:
      matchLabels:
        app: voipmonitor-gui
    volumeMounts:
    - mountPath: /var/www
      name: voipmonitor-gui-rook
  status:
    backupCount: 2
    firstBackupTime: 2018-01-26T07:34:32Z
    lastBackupDuration: 3.579814028s
    lastBackupTime: 2018-01-26T08:04:32Z
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

```

Then I try to test restore. I remove everything from /var/www inside my deploy container and make recovery like this.

```
---

apiVersion: stash.appscode.com/v1alpha1
kind: Recovery
metadata:
  name: voipmonitor-gui
  namespace: voipmonitor
spec:
  workload:
    kind: Deployment
    name: voipmonitor-gui
  backend:
    local:
      mountPath: /mnt/backup/stash
      hostPath:
        path: /mnt/backup/stash
    storageSecretName: voipmonitor-gui
  paths:
  - /var/www
  recoveredVolumes:
  - mountPath: /var/www
    name: voipmonitor-gui-rook

```
Then try to watch status of recovery. And it allways in running state and nothing appear in mounted volume in my deployment container.

```
apiVersion: v1
items:
- apiVersion: stash.appscode.com/v1alpha1
  kind: Recovery
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"stash.appscode.com/v1alpha1","kind":"Recovery","metadata":{"annotations":{},"name":"voipmonitor-gui","namespace":"voipmonitor"},"spec":{"backend":{"local":{"hostPath":{"path":"/mnt/backup/stash"},"mountPath":"/mnt/backup/stash"},"storageSecretName":"voipmonitor-gui"},"paths":["/var/www"],"recoveredVolumes":[{"mountPath":"/var/www","name":"voipmonitor-gui-rook"}],"workload":{"kind":"Deployment","name":"voipmonitor-gui"}}}
    clusterName: ""
    creationTimestamp: 2018-01-26T08:24:21Z
    generation: 0
    name: voipmonitor-gui
    namespace: voipmonitor
    resourceVersion: "2057636"
    selfLink: /apis/stash.appscode.com/v1alpha1/namespaces/voipmonitor/recoveries/voipmonitor-gui
    uid: 4f164bd4-0272-11e8-85c4-d43d7ed6ce3b
  spec:
    backend:
      local:
        hostPath:
          path: /mnt/backup/stash
        mountPath: /mnt/backup/stash
      storageSecretName: voipmonitor-gui
    paths:
    - /var/www
    recoveredVolumes:
    - mountPath: /var/www
      name: voipmonitor-gui-rook
    workload:
      kind: Deployment
      name: voipmonitor-gui
  status:
    phase: Running
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```
Here the logs of stash operator container

```
I0126 08:24:21.205044       1 recoveries.go:162] Sync/Add/Update for Recovery voipmonitor-gui
I0126 08:24:21.264925       1 jobs.go:109] Sync/Add/Update for Job stash-recovery-voipmonitor-gui
I0126 08:24:21.291576       1 serviceaccount.go:21] Creating ServiceAccount voipmonitor/stash-recovery-voipmonitor-gui.
I0126 08:24:21.533052       1 rolebinding.go:21] Creating RoleBinding voipmonitor/stash-recovery-voipmonitor-gui.
I0126 08:24:21.600353       1 recoveries.go:197] [Recovery job created: stash-recovery-voipmonitor-gui]
I0126 08:24:21.600927       1 recovery.go:56] Patching Recovery voipmonitor/voipmonitor-gui with {"status":{"phase":"Running"}}.
I0126 08:24:21.714211       1 recovery.go:90] [Updated recovery status: { []}]
I0126 08:24:22.578750       1 jobs.go:109] Sync/Add/Update for Job stash-recovery-voipmonitor-gui
I0126 08:24:28.077374       1 jobs.go:109] Sync/Add/Update for Job stash-recovery-voipmonitor-gui
I0126 08:24:28.077404       1 jobs.go:112] Deleting succeeded job stash-recovery-voipmonitor-gui
I0126 08:24:28.126502       1 jobs.go:123] Deleted stash job: stash-recovery-voipmonitor-gui
W0126 08:24:28.130615       1 jobs.go:105] Job voipmonitor/stash-recovery-voipmonitor-gui does not exist anymore
```

So what I do wrong? Or maybe this is the bug? How stash make a restore? There are more then one shapshot? which one he must restore? Is there any way to choose which snapshot it must restore. So now restore not working in my cluster. Any ideas?

**Comment by diptadas** [comment]
Hi @xpowerman, which version of stash operator are you using?
You need to provide a volume-source instead of name in recoveredVolumes.
See [here](https://github.com/appscode/stash/blob/master/docs/concepts/crds/recovery.md#specrecoveredvolumes)

**Comment by xpowerman** [comment]
I use 0.6.3 version. Did you mean that I need to write persistentvolume name, if I use rook storage with persistent volume claim? I write pvc name 
kubectl get pvc -n voipmonitor
```
NAME                   STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
voipmonitor-gui-rook   Bound     pvc-930c7f20-00ed-11e8-b17f-d43d7ed6ce3b   1000Mi     RWX            rook-block     4d
```

**Comment by diptadas** [comment]
```yaml
recoveredVolumes:
    - mountPath: /var/www
      persistentVolumeClaim:
          claimName: voipmonitor-gui-rook
```
You need to specify `claimName` as described [here](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#claims-as-volumes).

**Comment by diptadas** [comment]
Currently you can only restore the latest snapshot. We are working on restoring specific backup.

**Comment by xpowerman** [comment]
Ok. Thank you. Frequently when I delete and then create restic againg, I don't see status output.

```
apiVersion: v1
items:
- apiVersion: stash.appscode.com/v1alpha1
  kind: Restic
  metadata:
    clusterName: ""
    creationTimestamp: 2018-01-29T11:07:22Z
    name: voipmonitor-gui
    namespace: voipmonitor
    resourceVersion: "3157293"
    selfLink: /apis/stash.appscode.com/v1alpha1/namespaces/voipmonitor/restics/voipmonitor-gui
    uid: 94b9da01-04e4-11e8-8aa8-d43d7ed6ce3b
  spec:
    backend:
      local:
        hostPath:
          path: /mnt/backup/stash
        mountPath: /mnt/backup/stash
      storageSecretName: voipmonitor-gui
    fileGroups:
    - path: /var/www
      retentionPolicyName: keep-last-5
    retentionPolicies:
    - keepLast: 5
      name: keep-last-5
      prune: true
    schedule: '@every 30m'
    selector:
      matchLabels:
        app: voipmonitor-gui
    volumeMounts:
    - mountPath: /var/www
      name: voipmonitor-gui-rook
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```
In stash oerator log I see:

`I0129 11:07:23.042574       1 deployment.go:56] Patching Deployment voipmonitor/voipmonitor-gui with {"metadata":{"annotations":{"restic.appscode.com/last-applied-configuration":"{\"kind\":\"Restic\",\"apiVersion\":\"stash.appscode.com/v1alpha1\",\"metadata\":{\"name\":\"voipmonitor-gui\",\"namespace\":\"voipmonitor\",\"selfLink\":\"/apis/stash.appscode.com/v1alpha1/namespaces/voipmonitor/restics/voipmonitor-gui\",\"uid\":\"94b9da01-04e4-11e8-8aa8-d43d7ed6ce3b\",\"resourceVersion\":\"3157293\",\"creationTimestamp\":\"2018-01-29T11:07:22Z\"},\"spec\":{\"selector\":{\"matchLabels\":{\"app\":\"voipmonitor-gui\"}},\"fileGroups\":[{\"path\":\"/var/www\",\"retentionPolicyName\":\"keep-last-5\"}],\"backend\":{\"storageSecretName\":\"voipmonitor-gui\",\"local\":{\"hostPath\":{\"path\":\"/mnt/backup/stash\"},\"mountPath\":\"/mnt/backup/stash\"}},\"schedule\":\"@every 30m\",\"volumeMounts\":[{\"name\":\"voipmonitor-gui-rook\",\"mountPath\":\"/var/www\"}],\"resources\":{},\"retentionPolicies\":[{\"name\":\"keep-last-5\",\"keepLast\":5,\"prune\":true}]},\"status\":{}}\n","restic.appscode.com/tag":"0.6.3"}},"spec":{"template":{"spec":{"$setElementOrder/containers":[{"name":"gui"},{"name":"nginx"},{"name":"stash"}],"$setElementOrder/volumes":[{"name":"nginx-conf"},{"name":"php-fpm-conf"},{"name":"voipmonitor-gui-rook"},{"name":"stash-scratchdir"},{"name":"stash-podinfo"},{"name":"stash-local"}],"containers":[{"args":["backup","--restic-name=voipmonitor-gui","--workload-kind=Deployment","--workload-name=voipmonitor-gui","--run-via-cron=true","--pushgateway-url=http://stash-operator.stash.svc:56789","--analytics=true","--logtostderr=false","--alsologtostderr=false","--v=3","--stderrthreshold=0"],"env":[{"name":"NODE_NAME","valueFrom":{"fieldRef":{"fieldPath":"spec.nodeName"}}},{"name":"POD_NAME","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}},{"name":"APPSCODE_ANALYTICS_CLIENT_ID","value":"$gke$err$Get http://metadata.google.inter"}],"image":"appscode/stash:0.6.3","imagePullPolicy":"IfNotPresent","name":"stash","resources":{},"volumeMounts":[{"mountPath":"/tmp","name":"stash-scratchdir"},{"mountPath":"/etc/stash","name":"stash-podinfo"},{"mountPath":"/var/www","name":"voipmonitor-gui-rook","readOnly":true},{"mountPath":"/mnt/backup/stash","name":"stash-local"}]}],"volumes":[{"emptyDir":{},"name":"stash-scratchdir"},{"downwardAPI":{"items":[{"fieldRef":{"fieldPath":"metadata.labels"},"path":"labels"}]},"name":"stash-podinfo"},{"hostPath":{"path":"/mnt/backup/stash"},"name":"stash-local"}]}}}}`

And nothing happen. No files in path for snapshots. After deleting and recreating stash operator pods, sometimes it start working. Is it a bug or I do something wrong. It happen with restic from this ticket.

**Comment by tamalsaha** [comment]
@xpowerman, can you share the log for the `stash` sidecar ? Also, which cloud provider are you using? Can you please show `kubectl version` ?

**Comment by tamalsaha** [comment]
Please try the 0.7.0-rc.0 release. Reopen if you are still having problem.
