### ISSUE TITLE
Rename Restic to Backup

### ISSUE THREAD

**Issue by tamalsaha** [appscode/stash#320]

**Comment by whereisaaron** [comment]
I thought the same things the first time I tried `stash` but I thought it petty to bring it up :smile:
So yeah, I fully support this change. While `restic` is just great, no reason `stash` couldn't support `restic` and something else down the line (e.g. [`duplicacy`](https://github.com/gilbertchen/duplicacy), if @gilbertchen were to switch to a free software license for the command line at some point).

**Comment by tamalsaha** [comment]
In v1beta1 api, Restic is renamed to `BackupConfiguration`
https://github.com/appscode/stash/pull/647#issuecomment-461017921
