### ISSUE TITLE
Ability to backup volumes with ReadWriteOnce access mode

### ISSUE THREAD

**Issue by pastukhov** [appscode/stash#350]
Hello!
Is it possible to backup with stash content from PV that have ReadWriteOnce access mode?
Such as ceph-rbd volumes.

Thanks!

**Comment by whereisaaron** [comment]
Yes, because Stash is injected as a sidecar in the same Pod as the app that is using the PV, and so has access to the same PV's and the app, even the ReadWriteOnce ones.

**Comment by tamalsaha** [comment]
I have updated the readme to make this point clear. Thanks @whereisaaron !
