### ISSUE TITLE
Support for --stdin and --stdin-filename Restic backup options

### ISSUE THREAD

**Issue by ndarilek** [appscode/stash#351]
Just started using Restic, and I like how I can use the `--stdin` option when backing up to pipe the output of a database dump directly into a snapshot.

Might be nice to add something like:

```yaml
stdout: pg_dumpall
```

as an option instead of a list of files to back up? That command would then be exec'd in the container for which Stash is a sidekick. Obviously this would fail if the command does, or if the selector selects containers that do and don't include the specified binary. But for simpler cases of taking quick SQL backups this would seem like a better option than working some magic with offline or complex streaming backups. Might also be a good idea to support the option for setting the stdin filename, in cases where _stdin_ wouldn't be appropriate.

Thanks!

**Comment by diptadas** [comment]
Fixed by #694
