### ISSUE TITLE
[0.7.0-rc.0] Fails on start-up with 'cluster doesn't provide requestheader-client-ca-file'

### ISSUE THREAD

**Issue by whereisaaron** [appscode/stash#353]
Version 0.6.x is working find on my k8s 1.8.7 clusters (`kube-aws`), but wiping and redeploying with the 0.7.0-rc.0 container leads to a crash loop with the error: 'cluster doesn't provide requestheader-client-ca-file'.

```
F0226 05:29:49.344795       1 main.go:24] [Error in Stash Main: cluster doesn't provide requestheader-client-ca-file]
goroutine 1 [running]:
github.com/appscode/stash/vendor/github.com/golang/glog.stacks(0xc4202c4400, 0xc420362000, 0x76, 0xa0)
        /go/src/github.com/appscode/stash/vendor/github.com/golang/glog/glog.go:766 +0xcf
github.com/appscode/stash/vendor/github.com/golang/glog.(*loggingT).output(0x2532560, 0xc400000003, 0xc4200f3810, 0x2376b14, 0x7, 0x18, 0x0)
        /go/src/github.com/appscode/stash/vendor/github.com/golang/glog/glog.go:717 +0x30f
github.com/appscode/stash/vendor/github.com/golang/glog.(*loggingT).printDepth(0x2532560, 0x3, 0x1, 0xc42050bf10, 0x1, 0x1)
        /go/src/github.com/appscode/stash/vendor/github.com/golang/glog/glog.go:646 +0x129
github.com/appscode/stash/vendor/github.com/golang/glog.FatalDepth(0x1, 0xc42050bf10, 0x1, 0x1)
        /go/src/github.com/appscode/stash/vendor/github.com/golang/glog/glog.go:1131 +0x5d
github.com/appscode/stash/vendor/github.com/appscode/go/log.Fatalln(0xc420782be0, 0x2, 0x2)
        /go/src/github.com/appscode/stash/vendor/github.com/appscode/go/log/log.go:25 +0x9e
main.main()
        /go/src/github.com/appscode/stash/main.go:24 +0x115
```

**Comment by tamalsaha** [comment]
The issue is that the kube apiserver in your cluster does not have `--requestheader-client-ca-file` flag set.

From: https://kubernetes.io/docs/reference/generated/kube-apiserver/
```
--requestheader-client-ca-file string                     Root certificate bundle to use to verify client certificates on incoming requests before trusting usernames in headers specified by --requestheader-username-headers
```

Once you have set this up properly, please check that the configmap `extension-apiserver-authentication-reader` in kube-system namespace has key `requestheader-client-ca-file`.

```
kubectl describe configmap -n kube-system extension-apiserver-authentication
```

If you are new to the aggregation concept, please take a look at:
- https://github.com/kubernetes-incubator/apiserver-builder/blob/master/docs/concepts/aggregation.md
- https://github.com/kubernetes-incubator/apiserver-builder/blob/master/docs/concepts/auth.md

**Comment by whereisaaron** [comment]
Hi @tamalsaha thanks for the tips. These are `kube-aws` clusters and aggregation and `--requestheader-client-ca-file` are [configured automatically](https://github.com/kubernetes-incubator/kube-aws/blob/v0.9.9/core/controlplane/config/templates/cloud-config-controller#L2713) and the `extension-apiserver-authentication` ConfigMap is created (see below).

I have been deploying Stash in its own namespace, not `kube-system`. Is the code somehow assuming it is running in `kube-system`? The RBAC ClusterRole/Binding does allow ConfigMap access, should that be sufficient?

```
$ kubectl describe configmap -n kube-system extension-apiserver-authentication
Name:         extension-apiserver-authentication
Namespace:    kube-system
Labels:       <none>
Annotations:  <none>

Data
====
client-ca-file:
----
-----BEGIN CERTIFICATE-----
...redacted...
-----END CERTIFICATE-----

Events:  <none>
```

**Comment by tamalsaha** [comment]
So, we create a RoleBinding in kube-system namespace that gives the stash serviceaccount (in the installed namespace) read permission on this configmap.

chart: https://github.com/appscode/stash/blob/d70fc0b286bad15cc99f3f4ffdb4d88d7d1b7c09/chart/stable/stash/templates/apiregistration.yaml#L42

YAML: https://github.com/appscode/stash/blob/d70fc0b286bad15cc99f3f4ffdb4d88d7d1b7c09/hack/deploy/rbac-list.yaml#L95

Do you see this in your cluster?

**Comment by whereisaaron** [comment]
Yep, that is there. I am using the current/master `helm` chart.

```
$ kubectl --namespace=kube-system describe rolebinding stash-backup-
apiserver-extension-server-authentication-reader
Name:         stash-backup-apiserver-extension-server-authentication-reader
Labels:       app=stash
              chart=stash-0.3.0
              heritage=Tiller
              release=stash-backup
Annotations:  <none>
Role:
  Kind:  Role
  Name:  extension-apiserver-authentication-reader
Subjects:
  Kind            Name          Namespace
  ----            ----          ---------
  ServiceAccount  stash-backup  backup
```

**Comment by tamalsaha** [comment]
@whereisaaron , there was a bug in how service account name was used. It has been fixed here: https://github.com/appscode/stash/commit/cb573593845e7ce136c4fb900acac16c2d1e6325

Please try with the new chart from master and see if that fixes the issue.

**Comment by whereisaaron** [comment]
@tamalsaha I wiped everything and tried over with the latest chart, but no change in behaviour.

I deleted the entire deployment `helm delete --purge`. I updated the chart against master, the deployed with exactly the default values from the newest chart (`helm inspect values`). It crashes with the following error, even though all these exist (in `kube-system`):
- `configmap/extension-apiserver-authentication` 
- `rolebinding/stash-backup-apiserver-extension-server-authentication-reader`
- `role/extension-apiserver-authentication-reader`

I deleted everything again, and tried deploying in `kube-system`. but get the same error. This is with RBAC on k8s 1.8.7. Is the new chart 1.9.x only?

```
F0309 19:02:13.174282       1 main.go:24] [Error in Stash Main: cluster doesn't provide requestheader-client-ca-file]
goroutine 1 [running]:
github.com/appscode/stash/vendor/github.com/golang/glog.stacks(0xc4202ae600, 0xc4203a00a0, 0x76, 0xa0)
        /go/src/github.com/appscode/stash/vendor/github.com/golang/glog/glog.go:766 +0xcf
github.com/appscode/stash/vendor/github.com/golang/glog.(*loggingT).output(0x2532560, 0xc400000003, 0xc42010f970, 0x2376b14, 0x7, 0x18, 0x0)
        /go/src/github.com/appscode/stash/vendor/github.com/golang/glog/glog.go:717 +0x30f
github.com/appscode/stash/vendor/github.com/golang/glog.(*loggingT).printDepth(0x2532560, 0x3, 0x1, 0xc42045df10, 0x1, 0x1)
        /go/src/github.com/appscode/stash/vendor/github.com/golang/glog/glog.go:646 +0x129
github.com/appscode/stash/vendor/github.com/golang/glog.FatalDepth(0x1, 0xc42045df10, 0x1, 0x1)
        /go/src/github.com/appscode/stash/vendor/github.com/golang/glog/glog.go:1131 +0x5d
github.com/appscode/stash/vendor/github.com/appscode/go/log.Fatalln(0xc42033ffa0, 0x2, 0x2)
        /go/src/github.com/appscode/stash/vendor/github.com/appscode/go/log/log.go:25 +0x9e
main.main()
        /go/src/github.com/appscode/stash/main.go:24 +0x115
```

**Comment by whereisaaron** [comment]
The charts starts with this option blank `--requestheader-client-ca-file=""`, does that means it defaults to load from that `extension-apiserver-authentication` configmap?

`configmap/extension-apiserver-authentication` doesn't appear to be mounted anywhere

```
...
I0309 19:23:16.413860       1 logs.go:19] FLAG: --rbac="true"
I0309 19:23:16.413877       1 logs.go:19] FLAG: --requestheader-allowed-names="[]"
I0309 19:23:16.413892       1 logs.go:19] FLAG: --requestheader-client-ca-file=""
I0309 19:23:16.413904       1 logs.go:19] FLAG: --requestheader-extra-headers-prefix="[x-remote-extra-]"
I0309 19:23:16.413919       1 logs.go:19] FLAG: --requestheader-group-headers="[x-remote-group]"
I0309 19:23:16.413935       1 logs.go:19] FLAG: --requestheader-username-headers="[x-remote-user]"
I0309 19:23:16.413945       1 logs.go:19] FLAG: --resync-period="10m0s"
...
```

**Comment by whereisaaron** [comment]
@tamalsaha, putting this on hold I am going to double-check the apiserver arguments, looks like the options are on the metrics server only.

**Comment by tamalsaha** [comment]
> configmap/extension-apiserver-authentication doesn't appear to be mounted anywhere

This is not mounted rather Stash ([k8s.io/apiserver](https://github.com/kubernetes/apiserver/blob/66da060b9e5e1f415bbaff2c0956518656534ce8/pkg/server/options/authentication.go#L230)) loads it via Kubernetes api. Hence the RBAC is required.

**Comment by whereisaaron** [comment]
Right, well I think I have solved this and you were right in the first the place; The `apiserver` did not have the right options, I was fooled when I grep'd the stack for the options because there were on the metric server (but not on the `apiserver`).

I added the following options to the `apiserver` on the controller nodes, and now 0.7.0-rc.0 runs when deployed with the helm chart. I haven't really tested it yet, but we are running at least.

```
...
    - --requestheader-client-ca-file=/etc/kubernetes/ssl/ca.pem
    - --requestheader-allowed-names=
    - "--requestheader-extra-headers-prefix=X-Remote-Extra-"
    - --requestheader-group-headers=X-Remote-Group
    - --requestheader-username-headers=X-Remote-User
...
```

**Comment by tamalsaha** [comment]
Glad that you got it running finally. Please note that the ca file used for `--requestheader-client-ca-file` should be different from the `client-ca-file` used by kubectl. Otherwise, anyone can spoof the auth headers.

**Comment by whereisaaron** [comment]
Yeah I wondered about exactly that. Those setting are straight from the examples people provided and I had supposed we were supposed to limit the trusted certificates through a list of CNs in `requestheader-allowed-names`.

But it should be a whole separate CA? `requestheader-client-ca-file` is just just the public cert, so there are no certficiates signed by it? Do I then need to provide a signed certficate for Stash? Or do I just sign a cert and configure the proxy cert/key? In that case, the proxy configuration is really mandatory?
```
--proxy-client-cert-file=<path to aggregator proxy cert>
--proxy-client-key-file=<path to aggregator proxy key>
```
I also don't understand why the clusters already had a `extension-apiserver-authentication` configmap with a cert in it, even though the `-requestheader-client-ca-file` didn't appear to be set?


The minimal official doc breally doesn't cover what is needed:
https://kubernetes.io/docs/tasks/access-kubernetes-api/configure-aggregation-layer/

The API option list is actually the most detail doc  I've found :-)
https://kubernetes.io/docs/reference/generated/kube-apiserver/

> --proxy-client-cert-file string
> Client certificate used to prove the identity of the aggregator or kube-apiserver when it must call out during a request. This includes proxying requests to a user api-server and calling out to webhook admission plugins. It is expected that this cert includes a signature from the CA in the --requestheader-client-ca-file flag. That CA is published in the 'extension-apiserver-authentication' configmap in the kube-system namespace. Components receiving calls from kube-aggregator should use that CA to perform their half of the mutual TLS verification.

> --proxy-client-key-file string
> Private key for the client certificate used to prove the identity of the aggregator or kube-apiserver when it must call out during a request. This includes proxying requests to a user api-server and calling out to webhook admission plugins.

> --requestheader-allowed-names stringSlice
> List of client certificate common names to allow to provide usernames in headers specified by --requestheader-username-headers. If empty, any client certificate validated by the authorities in --requestheader-client-ca-file is allowed.

> --requestheader-client-ca-file string
> Root certificate bundle to use to verify client certificates on incoming requests before trusting usernames in headers specified by --requestheader-username-headers

**Comment by tamalsaha** [comment]
I am going to try to explain why you need a separate CA for request header. When an extended api server is used, this is what a `kubectl get ***` looks like:

```
kubectl -----(1)-----> Kube api server -----(2)-----> Extended api server (EAS)
```

In step `(1)`, the main kube api server uses a CA certificate signed by the `client-ca-file`. This is the CA file that is also present in you local ~/.kube/config file. So, when kubectl calls kube api server, it can trust the identify of the api server.

Now, if you are using a Kubernetes object that is provided by EAS, the main server can identify that using the information provided by EAS during the [`APIService`](https://github.com/appscode/stash/blob/master/hack/deploy/operator.yaml#L111) registration phase.

Once the kube server has performed AuthN and AuthZ to confirm that client (kubectl) has perform to perform the operation, the kube api server will proxy that request to EAS using mutual TLS. 

- EAS provides its side of the identify using CA that is provides to kube api server in the APIService `cabundle`.

- Kube api server provides its side of the identify using the `requestheader-ca` and `UserInfo` using the `X-Remote-***`  header. EAS can automatically learn about the `requestheader-ca` and `X-Remote-***` by [reading](https://github.com/appscode/stash/blob/master/hack/deploy/rbac-list.yaml#L95) the `extension-apiserver-authentication` configmap. This simplifies the setup process for EAS.

Inside of a kuberentes cluster, the requestheader-client-ca file is used to identify a request that is asserting identity.  That CA file is not used to identify a subject on a request directly.  the `--client-ca` file is used for that. 

If you use same CA for both `client-ca` and `requestheader-ca`, any client of your cluster who uses client cert auth can spoof any other user. Say, Bob has perform to edit objects provides by EAS. Alice does not have perform to do so. But Alice uses client-cert to run kubectl commands. Now, Alice can make a direct api call to EAS using her client cert with `X-Remote-User: Bob` and use Bob's permission.
```
kubectl (Alice) -------X-Remote-Header=Bob ------> EAS
```

This is why you need separate CA's for `requestheader-ca` and `client-ca`.

**Comment by tamalsaha** [comment]
> I just sign a cert and configure the proxy cert/key?

Looking at the [code for Kubernetes aggregation layer](https://github.com/kubernetes/kube-aggregator/blob/master/pkg/cmd/server/start.go#L138), it seems to me that you need to provide  `--proxy-client-cert-file` and `--proxy-client-key-file` files signed by `requestheader-ca`.

> I also don't understand why the clusters already had a extension-apiserver-authentication configmap with a cert in it, even though the -requestheader-client-ca-file didn't appear to be set?

My sense is that `extension-apiserver-authentication` is designed as a way to automatically discover trust information for a Kubernetes cluster. So, this configmap should be safe to make publicly readable (system:anonymous group). This can CA for `client-ca` (always) and `requestheader-ca` (if enabled).
