### ISSUE TITLE
[0.6.x] Helm chart broken due to undocumented '--docker-registry' and other arguments

### ISSUE THREAD

**Issue by whereisaaron** [appscode/stash#354]
Trying to revert to 0.6.x fails because the chart has had an apparently required arguments added to the Deployment, but none of them are in `values.yaml` or documented in the chart `README.md`. There are several, like `--docker-register`, `--secure-port`, `--audit-log-flag`, `--tls-cert-file`, `--tls-cert-private-key`.

Look like [this patch](https://github.com/appscode/stash/commit/050c99917236b64d5432e8237a2bd8f65e8812cd#diff-8a448ad58f5c2ae8cf36456aa04a9e6aR41) added the problem argument:
https://github.com/appscode/stash/commit/050c99917236b64d5432e8237a2bd8f65e8812cd#diff-8a448ad58f5c2ae8cf36456aa04a9e6aR41

```
        args:
        - run
        - --v=3
        - --rbac={{ .Values.rbac.create }}
        - --docker-registry={{ .Values.dockerRegistry }}
        - --secure-port=8443
        - --audit-log-path=-
        - --tls-cert-file=/var/serving-cert/tls.crt
        - --tls-private-key-file=/var/serving-cert/tls.key
```

If 0.6.x does not need these, then the chart should not add them if not values is supplied in `values.yaml`, e.g.

```
        args:
        - run
        - --v=3
        - --rbac={{ .Values.rbac.create }}
        {{- if not .Values.dockerRegistry }}
        - --docker-registry={{ .Values.dockerRegistry }}
        - --secure-port=8443
        - --audit-log-path=-
        - --tls-cert-file=/var/serving-cert/tls.crt
        - --tls-private-key-file=/var/serving-cert/tls.key
        {{- end }}
```

**Comment by whereisaaron** [comment]
Look like health probe needs to be different too, if there is no `--secure-port` for 0.6.x deploys.

```
  Warning  Unhealthy              6s (x9 over 1m)  kubelet, ip-172-27-22-235.ap-southeast-2.compute.internal  Readiness probe failed: Get https://10.20.96.28:8443/healthz: dial tcp 10.20.96.28:8443: getsockopt: connection refused
```

**Comment by tamalsaha** [comment]
Please reopen if using the chart from release-0.6 does not solve this issue.
