### ISSUE TITLE
Allow default backup

### ISSUE THREAD

**Issue by tamalsaha** [appscode/stash#367]
We could mark a Restic object as default. If a deployment does not have a specific Restic match, it will be use this default Restic to perform backup.

This will give user's default opt-in to backup ability. If they want to opt-out, they can pause their specific Restic or mark deployments will pause annotation.

**Comment by tamalsaha** [comment]
From @arjunsbabu via slack, 

for default restic there are some issues  i guess:

1. Deployments have different mount points for PV.So a single restic deployment cannot use for all workloads
2. all deployments dont need backup..If custiemr ask for backup then only we need to implement it

**Comment by tamalsaha** [comment]
One option will be to create `RsticTemplate` that can be filled in via annotations from the Deployment.

**Comment by arjunsbabu** [comment]
@tamalsaha id possible can you give an example template

**Comment by tamalsaha** [comment]
https://appscode.slack.com/archives/DAFPBQP6Z/p1536068077000100

**Comment by hossainemruz** [comment]
Default backup is supported in `v1beta1` design. It requires one `BackupConfigurationTemplate` that specifies template for `Repository` and `BackupConfiguration` crd and some annotations in workload that will be backed up.

v1beta1 design discussion: https://github.com/appscode/stash/issues/648

Reference PRs: #647 #674 #675
