### ISSUE TITLE
"DeprecatedServiceAccount not present in src" while converting unversioned StatefulSet to v1beta1.StatefulSet 

### ISSUE THREAD

**Issue by emruz-hossain** [appscode/stash#371]
While trying to convert **unversioned** `StatefulSet` to `v1beta1.StatefulSet` getting this error.
```
error: Scaling the resource failed with: Internal error occurred: admission webhook
"admission.stash.appscode.com" denied the request: converting
(apps.StatefulSet).Template.Spec.ServiceAccountName to
(v1beta1.StatefulSet).Template.Spec.ServiceAccountName: DeprecatedServiceAccount not present in src; Current resource version 14469
```
`ServiceAccountName` is empty in unversioned type. YAML for my unversioned StatefulSet is [here](https://gist.github.com/emruz-hossain/30be298069c23ca8f08852c82e55d72b)

**Comment by tamalsaha** [comment]
Fixed after using legacyscheme, @emruz-hossain  ?
