### ISSUE TITLE
Backup/restore database (KubeDB integration)

### ISSUE THREAD

**Issue by pierreozoux** [appscode/stash#388]
How do you backup such volumes?
The volume in itself is not really interesting, we need to dump data first.

What about puting a label on such volumes, and do a dump instead?

**Comment by galexrt** [comment]
Even though it is a pretty "dirty" hack, you can do something like that:
```

**Comment by pierreozoux** [comment]
Thanks @galexrt for your kind answer, maybe my question was not really clear.
More than the implementation (there is also this [PR opened for mysql](https://github.com/kubernetes/charts/pull/4069) )
I'm more interested in a systematic solution. How do we dump database data before backup?

This is related to this question, [how do we do automatic backup](https://github.com/kubernetes/charts/issues/3896), and as this repository solves this in an elegant manner, the next question is, how do we do dumps before the backups, and how do we standardize this procedure.

This is highly hypothetic at this stage, but here is an example workflow:
 - mysql chart ship with the backup job 
 - backup:
   - mysq volume is tagged to not be backed up
   - mysql dump volume is tagged to be backed up
   - stash backup the mysql dump volume
 - restore
   - stash restores the mysql dump volume
   - the mysql container understand it has to restore the dump

Probably we'd need some more primitives to work on these topics :)
Maybe a `backup` and `dump` CRD to start with, then a backup controller, where `stash` could be one implementation.
And finally, a dump/restore controller for mysql shipped with the mysql chart.

All f this is of course highly hypothetic and would be nice in an ideal world!

But once we have that, we coudl replace mysql with postgres, mongo, mariadb, elastic..

**Comment by tamalsaha** [comment]
@pierreozoux , for database backups we recommend using something like https://kubedb.com . Database backups usually require using db level tools for safe backup and restore.

**Comment by Miouge1** [comment]
@pierreozoux I don't think that 2 volumes are needed. You can use `spec.fileGroups` to filter only the backup folder on your DB volume.

Also this can be solved with #351

**Comment by Miouge1** [comment]
As a feature proposal Stash could pick-up annotations like:
```
annotations:
  stash.appscode.com/backup-cmd-stdout: "mysqldump"
  stash.appscode.com/restore-cmd-stdin: "mysql"
```
That could trigger the `mysqldump` command (or whatever script you want) and backup the output (stdout) of that.
On the restore side, it would the the `mysql` command and pass the backup file as a `stdin`.

**Comment by pierreozoux** [comment]
@Miouge1 actually, `appscode` also has `kubedb` project that does dumps and restore automatically.

It is just about integrating kubedb dump and stash features.
I don't know yet what should be done, but for sure, there is a better way than now. Come to the slack channel of kubedb if you have some idea on how we could improve the process!

**Comment by Miouge1** [comment]
I plan to backup PVCs used for OpenLDAP, cockroachdb, redis, and mysql. AFAIK KubeDB covers only MySQL/Postgres/Redis. So a generic command thing would be really helpful.

**Comment by tamalsaha** [comment]
xref: https://github.com/kubedb/project/issues/168

**Comment by giovannicandido** [comment]
This would also solve consul snapshots, not only databases. I like the idea of central backup tool with one source for management, monitoring and alerts.

Stash could pipe the stream to restic and "tag" the backup with the date and time. When a restore is necessary the restore command will receive the pipe from a specific backup file.

**Comment by tamalsaha** [comment]
Design is finalized here: https://github.com/appscode/stash/issues/648

**Comment by tamalsaha** [comment]
Dup https://github.com/appscode/stash/issues/648
