### ISSUE TITLE
Pod restart after each backup when Mutating Webhook enabled

### ISSUE THREAD

**Issue by emruz-hossain** [appscode/stash#396]
Pod restart after each backup when Mutating Webhook is enabled.
**Stash Version:** 0.7.0-rc.2
**kubectl version:** v1.9.0
**How to recreate ?**
1. Install stash with --enable-mutating-webhook
2. Create Restic.
3. Create a deployment that has label that match Restic selector.
 
Now, after each backup the pod will restart.

**Reason:**
Reason is not clear yet. It seems every time there is an unexpected `type:""` filed toggle between oldRestic and NewRestic.
Here is backend part oldRestic.
```
  "backend": {
         "storageSecretName": "local-secret",
         "local": {
            "hostPath": {
               "path": "/data/stash-test/restic-repo",
               "type": ""
            },
            "mountPath": "/safe/data"
         }
      },
```
Here is backend part of newRestic
```
  "backend": {
         "storageSecretName": "local-secret",
         "local": {
            "hostPath": {
               "path": "/data/stash-test/restic-repo"
            },
            "mountPath": "/safe/data"
         }
      },
```
This two part seems to be interchange after each backup. This cause patch deployment after every backup.  `resourceVersion` of Restic is changed after every backup. As  `resourceVersion` of Restic is used as annotation of Pod, it restart after each backup.

**Comment by tamalsaha** [comment]
```
This cause patch deployment after every backup. resourceVersion of Restic is changed after every backup. As resourceVersion of Restic is used as annotation of Pod, it restart after each backup.
```
I think that is the problem

**Comment by tamalsaha** [comment]
```
type ResticStatus struct {
	FirstBackupTime          *metav1.Time `json:"firstBackupTime,omitempty"`
	LastBackupTime           *metav1.Time `json:"lastBackupTime,omitempty"`
	LastSuccessfulBackupTime *metav1.Time `json:"lastSuccessfulBackupTime,omitempty"`
	LastBackupDuration       string       `json:"lastBackupDuration,omitempty"`
	BackupCount              int64        `json:"backupCount,omitempty"`
}
```

**Comment by tamalsaha** [comment]
This changes after every backup. So, causes restarts.
