### ISSUE TITLE
hack/deploy/stash.sh: $? check does not work with set -e

### ISSUE THREAD

**Issue by xanonid** [appscode/stash#403]
https://github.com/appscode/stash/blob/248bba9405c1c226b27b3617eaba38232cf9815f/hack/deploy/stash.sh#L2
https://github.com/appscode/stash/blob/248bba9405c1c226b27b3617eaba38232cf9815f/hack/deploy/stash.sh#L60

**Comment by tamalsaha** [comment]
Fixed https://github.com/appscode/stash/pull/404
