### ISSUE TITLE
Use one repository per workload

### ISSUE THREAD

**Issue by tamalsaha** [appscode/stash#439]
@galexrt brought up this issue on Slack. Here are some questions answered by @fd0 . 

https://forum.restic.net/t/what-are-the-implications-of-storing-data-from-different-hosts-in-one-repository/589

This is a tracker issue. We need to think through the process and come up with a plan.

**Comment by hossainemruz** [comment]
Stash `v1beta1` design use 1:1 mapping between workload and repository.

Stash `v1beta1` design discussion: https://github.com/appscode/stash/issues/648
