### ISSUE TITLE
Backup not triggered 

### ISSUE THREAD

**Issue by arjunsbabu** [appscode/stash#461]
Hi Team,
The kubernetes environment is based on IBM cloud private 2.1.0.2
k8 version 1.9.1
The installation of stash is done using the command
 curl -fsSL https://raw.githubusercontent.com/appscode/stash/0.7.0-rc.3/hack/deploy/stash.sh | bash -s -- --enable-validating-webhook=false --enable-mutating-webhook=false

For backing up the volume i followed the link https://appscode.com/products/stash/0.7.0-rc.3/guides/backup/
The stash container is created but the backup is not starting.
`root@inmbzp4159:~/.kube# kubectl logs stash-demo-85fd6dcd4c-cb8tj -c stash
I0502 08:56:43.846014       1 logs.go:19] FLAG: --alsologtostderr="false"
I0502 08:56:43.846374       1 logs.go:19] FLAG: --docker-registry="appscode"
I0502 08:56:43.846393       1 logs.go:19] FLAG: --enable-analytics="true"
I0502 08:56:43.846401       1 logs.go:19] FLAG: --enable-rbac="false"
I0502 08:56:43.846407       1 logs.go:19] FLAG: --help="false"
I0502 08:56:43.846414       1 logs.go:19] FLAG: --image-tag="0.7.0-rc.3"
I0502 08:56:43.846420       1 logs.go:19] FLAG: --kubeconfig=""
I0502 08:56:43.846429       1 logs.go:19] FLAG: --log_backtrace_at=":0"
I0502 08:56:43.846436       1 logs.go:19] FLAG: --log_dir=""
I0502 08:56:43.846443       1 logs.go:19] FLAG: --logtostderr="false"
I0502 08:56:43.846449       1 logs.go:19] FLAG: --master=""
I0502 08:56:43.846457       1 logs.go:19] FLAG: --pushgateway-url="http://stash-operator.kube-system.svc:56789"
I0502 08:56:43.846464       1 logs.go:19] FLAG: --restic-name="stash-demo"
I0502 08:56:43.846473       1 logs.go:19] FLAG: --resync-period="5m0s"
I0502 08:56:43.846480       1 logs.go:19] FLAG: --run-via-cron="true"
I0502 08:56:43.846490       1 logs.go:19] FLAG: --scratch-dir="/tmp"
I0502 08:56:43.846496       1 logs.go:19] FLAG: --stderrthreshold="0"
I0502 08:56:43.846503       1 logs.go:19] FLAG: --v="3"
I0502 08:56:43.846509       1 logs.go:19] FLAG: --vmodule=""
I0502 08:56:43.846516       1 logs.go:19] FLAG: --workload-kind="Deployment"
I0502 08:56:43.846525       1 logs.go:19] FLAG: --workload-name="stash-demo"
W0502 08:56:44.495563       1 client_config.go:529] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0502 08:56:44.803754       1 backup.go:71] [Running backup periodically via cron]
I0502 08:56:44.803847       1 leaderelection.go:174] attempting to acquire leader lease...
I0502 08:56:45.035368       1 leaderelection.go:184] successfully acquired lease default/lock-deployment-stash-demo
I0502 08:56:45.035467       1 scheduler.go:80] [Got leadership, preparing backup backup]
root@inmbzp4159:~/.kube#
`
Seems like the stash container is not having the kubeconfig.

**Comment by tamalsaha** [comment]
TODO:
- [ ] --enable-rbac flag is passed to sidecar.
- [ ] "ie if iam using apiVersion: apps/v1  the sidecar is not attaching to the pod. but apiVersion: extensions/v1beta1 will works...Why is this ?"

**Comment by eliasp** [comment]
Looks like I'm seeing the same problem here:
- K8S v1.10.2
- Stash 0.7.0-rc.3

I've doublechecked the secrets - they look good but I suspect they can't be retrieved due to the `Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.` effects.

```
# kubectl logs ds-0 stash 
I0512 18:36:44.168228       1 logs.go:19] FLAG: --alsologtostderr="false"
I0512 18:36:44.170819       1 logs.go:19] FLAG: --docker-registry="appscode"
I0512 18:36:44.170906       1 logs.go:19] FLAG: --enable-analytics="true"
I0512 18:36:44.170927       1 logs.go:19] FLAG: --enable-rbac="false"
I0512 18:36:44.170948       1 logs.go:19] FLAG: --help="false"
I0512 18:36:44.170986       1 logs.go:19] FLAG: --image-tag="0.7.0-rc.3"
I0512 18:36:44.171010       1 logs.go:19] FLAG: --kubeconfig=""
I0512 18:36:44.171038       1 logs.go:19] FLAG: --log_backtrace_at=":0"
I0512 18:36:44.171080       1 logs.go:19] FLAG: --log_dir=""
I0512 18:36:44.171100       1 logs.go:19] FLAG: --logtostderr="false"
I0512 18:36:44.171119       1 logs.go:19] FLAG: --master=""
I0512 18:36:44.171155       1 logs.go:19] FLAG: --pushgateway-url="http://stash-operator.default.svc:56789"
I0512 18:36:44.171175       1 logs.go:19] FLAG: --restic-name="backup-directoryserver"
I0512 18:36:44.171196       1 logs.go:19] FLAG: --resync-period="5m0s"
I0512 18:36:44.171232       1 logs.go:19] FLAG: --run-via-cron="true"
I0512 18:36:44.171257       1 logs.go:19] FLAG: --scratch-dir="/tmp"
I0512 18:36:44.171276       1 logs.go:19] FLAG: --stderrthreshold="0"
I0512 18:36:44.171311       1 logs.go:19] FLAG: --v="3"
I0512 18:36:44.171331       1 logs.go:19] FLAG: --vmodule=""
I0512 18:36:44.171350       1 logs.go:19] FLAG: --workload-kind="StatefulSet"
I0512 18:36:44.171385       1 logs.go:19] FLAG: --workload-name="ds"
W0512 18:36:44.473561       1 client_config.go:529] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0512 18:36:44.603009       1 backup.go:71] [Running backup periodically via cron]
I0512 18:36:44.621746       1 backup.go:210] Found restic backup-directoryserver
I0512 18:36:44.639101       1 backup.go:218] Found repository secret first-backup-secret
E0512 18:36:45.928647       1 restic.go:186] Error running command '/bin/restic [snapshots --json --cache-dir /tmp/restic-cache]' output:
[golang-sh]$ /bin/restic snapshots --json --cache-dir /tmp/restic-cache
Fatal: unable to open repo at b2:first-backup:/opendj/statefulset/ds-0: b2.NewClient: b2_authorize_account: 401: Invalid authorization token

E0512 18:36:47.236137       1 restic.go:186] Error running command '/bin/restic [init --cache-dir /tmp/restic-cache]' output:
[golang-sh]$ /bin/restic init --cache-dir /tmp/restic-cache
Fatal: create repository at b2:first-backup:/opendj/statefulset/ds-0 failed: b2.NewClient: b2_authorize_account: 401: Invalid authorization token


F0512 18:36:47.236189       1 backup.go:73] [failed to setup backup. Error: ]
goroutine 1 [running]:
github.com/appscode/stash/vendor/github.com/golang/glog.stacks(0xc420420d00, 0xc4201780b0, 0x4e, 0xa1)
        /go/src/github.com/appscode/stash/vendor/github.com/golang/glog/glog.go:766 +0xcf
github.com/appscode/stash/vendor/github.com/golang/glog.(*loggingT).output(0x288c960, 0xc400000003, 0xc420d54210, 0x26cce33, 0x9, 0x49, 0x0)
        /go/src/github.com/appscode/stash/vendor/github.com/golang/glog/glog.go:717 +0x30f
github.com/appscode/stash/vendor/github.com/golang/glog.(*loggingT).printDepth(0x288c960, 0x3, 0x1, 0xc420eafac8, 0x1, 0x1)
        /go/src/github.com/appscode/stash/vendor/github.com/golang/glog/glog.go:646 +0x129
github.com/appscode/stash/vendor/github.com/golang/glog.FatalDepth(0x1, 0xc420eafac8, 0x1, 0x1)
        /go/src/github.com/appscode/stash/vendor/github.com/golang/glog/glog.go:1131 +0x5d
github.com/appscode/stash/vendor/github.com/appscode/go/log.Fatal(0xc42075a1f0, 0x1, 0x1)
        /go/src/github.com/appscode/stash/vendor/github.com/appscode/go/log/log.go:21 +0x9e
github.com/appscode/stash/pkg/cmds.NewCmdBackup.func1(0xc4200ca280, 0xc4200b5380, 0x0, 0xc)
        /go/src/github.com/appscode/stash/pkg/cmds/backup.go:73 +0xa19
github.com/appscode/stash/vendor/github.com/spf13/cobra.(*Command).execute(0xc4200ca280, 0xc4200b4f00, 0xc, 0xc, 0xc4200ca280, 0xc4200b4f00)
        /go/src/github.com/appscode/stash/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/appscode/stash/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420393400, 0xc4200cb900, 0xc4200cb180, 0xc4200ca280)
        /go/src/github.com/appscode/stash/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/appscode/stash/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420393400, 0x1, 0x0)
        /go/src/github.com/appscode/stash/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
        /go/src/github.com/appscode/stash/main.go:23 +0x77
```

**Comment by tamalsaha** [comment]
RBAC issue was resolved.
PSP issue is tracked here: https://github.com/appscode/stash/issues/462
