### ISSUE TITLE
Stash restore pod fails with istio sidecar

### ISSUE THREAD

**Issue by farcaller** [appscode/stash#475]
Given a namespace that has istio injector enabled, stash restore pod fails with:

```
I0506 11:24:58.590370       1 logs.go:19] FLAG: --alsologtostderr="false"
I0506 11:24:58.590813       1 logs.go:19] FLAG: --enable-analytics="false"
I0506 11:24:58.590827       1 logs.go:19] FLAG: --help="false"
I0506 11:24:58.590835       1 logs.go:19] FLAG: --kubeconfig=""
I0506 11:24:58.590844       1 logs.go:19] FLAG: --log_backtrace_at=":0"
I0506 11:24:58.590849       1 logs.go:19] FLAG: --log_dir=""
I0506 11:24:58.590855       1 logs.go:19] FLAG: --logtostderr="false"
I0506 11:24:58.590860       1 logs.go:19] FLAG: --master=""
I0506 11:24:58.590866       1 logs.go:19] FLAG: --recovery-name="test"
I0506 11:24:58.590872       1 logs.go:19] FLAG: --stderrthreshold="0"
I0506 11:24:58.590877       1 logs.go:19] FLAG: --v="3"
I0506 11:24:58.590883       1 logs.go:19] FLAG: --vmodule=""
W0506 11:24:58.591084       1 client_config.go:529] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
E0506 11:24:58.600781       1 recovery.go:41] [Get https://10.200.0.1:443/apis/stash.appscode.com/v1alpha1/namespaces/test-ns/recoveries/test: dial tcp 10.200.0.1:443: connect: connection refused]
I0506 11:24:58.601047       1 main.go:26] [Exiting Stash Main]
```

One theory I have is that there's a race condition with istio sidecar and stash is just too fast. Istio's envoy doesn't have time to spin up and start serving outbound connections and everything fails.

One option to fix this would be to retry the connection to apiserver?

**Comment by farcaller** [comment]
Might be related to https://github.com/istio/istio/issues/1685

**Comment by farcaller** [comment]
No; not related to that bug after all. Running istio 0.7.1 here and I tried a dedicated pod with stash's serviceaccount and curl works there.

**Comment by farcaller** [comment]
It looks like a race indeed:

```
E0507 14:54:29.789669       1 recovery.go:41] [Get https://10.200.0.1:443/apis/stash.appscode.com/v1alpha1/namespaces/test-ns/recoveries/test: dial tcp 10.200.0.1:443: connect: connection refused]
```

all while

```
[2018-05-07 14:54:30.362][11][info][upstream] external/envoy/source/server/lds_api.cc:60] lds: add/update listener 'tcp_10.200.0.1_443'
```

**Comment by tamalsaha** [comment]
> Would it be reasonable to re-try the connection in stash? I'd expect more people hit that as stash is used in istio-based environments.

I think that makes sense. All the cli can have a wait until connect timeout field. The timeout can be zero for non-Istio setups. Can be set to > 0 for istio env. This flag can be added to root command https://github.com/appscode/stash/blob/master/pkg/cmds/root.go#L52 and implemented in the PersistentPreRun method.

Do you want to try that?
