### ISSUE TITLE
Using Stash with TLS secured Minio Server Can't succeed

### ISSUE THREAD

**Issue by zhwenh** [appscode/stash#478]
Using Stash with TLS secured Minio Server 
Refer to this document settings
https://appscode.com/products/stash/0.7.0-rc.3/guides/minio_server/

show errors：

Found repository secret s3-secret
--
  | E0511 02:47:43.324419       1 restic.go:186] Error running command '/bin/restic [snapshots --json --cache-dir /tmp/restic-cache]' output:
  | [golang-sh]$ /bin/restic snapshots --json --cache-dir /tmp/restic-cache
  | Fatal: unable to open config file: Stat: Get https://10.10.24.90:9000/stash-qa/?location=:  net/http: invalid header field value "AWS4-HMAC-SHA256 Credential=minio\n/20180511/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=398ac2b35fa6e7aae85970ce1627463b6a81b308cad8d8c618f4c49899e1c9db" for key Authorization
  | Is there a repository at the following location?
  | s3:https://10.10.24.90:9000/stash-qa/demo/deployment/stash-demo
  | E0511 02:47:43.330040       1 restic.go:186] Error running command '/bin/restic [init --cache-dir /tmp/restic-cache]' output:
  | [golang-sh]$ /bin/restic init --cache-dir /tmp/restic-cache
  | Fatal: create repository at s3:https://10.10.24.90:9000/stash-qa/demo/deployment/stash-demo  failed: client.BucketExists: Get https://10.10.24.90:9000/stash-qa/?location=:  net/http: invalid header field value "AWS4-HMAC-SHA256 Credential=minio\n/20180511/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=398ac2b35fa6e7aae85970ce1627463b6a81b308cad8d8c618f4c49899e1c9db" for key Authorization

**Comment by tamalsaha** [comment]
Closing, since no response. Please reopen if you have more to share.
