### ISSUE TITLE
Internal error occurred: failed calling admission webhook "deployment.admission.stash.appscode.com": the server could not find the requested resource

### ISSUE THREAD

**Issue by konfiot** [appscode/stash#510]
Hello,
I tried to install stash, but now I get an error : ```Internal error occurred: failed calling admission webhook "deployment.admission.stash.appscode.com": the server could not find the requested resource``` everytime I try to do anything (I can't even delete the replicasets and deployments...
Do you have any idea what's happening ?
Thanks a lot for all the work !

**Comment by tamalsaha** [comment]
Hi,
- What is your `kubectl version?`
- How did you provision your cluster?
- Can you download `onessl` from https://github.com/kubepack/onessl/releases/tag/0.5.0 and run the `onessl doctor --v=10` command?

**Comment by konfiot** [comment]
Hello,
I've got kubectl v1.10.4 (client is v1.10.4 and server is v1.10.2) : 
```$ kubectl version  
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:10:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cluster has been provisionned with kubeadm on bare metal
```
$ onessl doctor --v=10
cluster info:
apiServers:
- admissionControl:
  - NamespaceLifecycle
  - LimitRanger
  - ServiceAccount
  - DefaultStorageClass
  - DefaultTolerationSeconds
  - NodeRestriction
  - MutatingAdmissionWebhook
  - ValidatingAdmissionWebhook
  - ResourceQuota
  allowPrivileged: true
  authorizationMode:
  - Node
  - RBAC
  clientCAData: |-
    -----BEGIN CERTIFICATE-----
   <cert>
    -----END CERTIFICATE-----
  featureGates: {}
  hostIP: <master_ip>
  nodeName: blokad
  podIP: <master_ip>
  podName: kube-apiserver-blokad
  requestHeaderCAData: |-
    -----BEGIN CERTIFICATE-----
    <cert>
    -----END CERTIFICATE-----
  runtimeConfig: {}
capabilities:
  aggregateAPIServer: true
  apiVersion: 1.10.0
  customResourceSubresources: unknown
  initializers: "false"
  mutatingAdmissionWebhook: "true"
  podSecurityPolicy: "false"
  validatingAdmissionWebhook: "true"
clientConfig:
  Host: https://<master_ip>:6443
  caData: |-
    -----BEGIN CERTIFICATE-----
    <cert>
    -----END CERTIFICATE-----
extensionServerConfig:
  clientCAData: |-
    -----BEGIN CERTIFICATE-----
    <cert>
    -----END CERTIFICATE-----
  requestHeaderConfig:
    allowedClientNames:
    - front-proxy-client
    caData: |-
      -----BEGIN CERTIFICATE-----
    <cert>
      -----END CERTIFICATE-----
    extraHeaderPrefixes:
    - X-Remote-Extra-
    groupHeaders:
    - X-Remote-Group
    usernameHeaders:
    - X-Remote-User
version:
  buildDate: 2018-04-27T09:10:24Z
  gitCommit: 81753b10df112992bf51bbc2c2f85208aad78335
  gitVersion: v1.10.2
  minor: 1.10.0
  patch: 1.10.2
  platform: linux/amd64
```

I've managed to nuke the deployment with the uninstall script finally, trying to reinstall it

**Comment by konfiot** [comment]
Also, when I try to reinstall it (using helm chart) it installs in the default namespace, not in kube-system

**Comment by tamalsaha** [comment]
Also, you can join our slack https://slack.appscode.com/ and ask me @tamal . We can take a look at the issue. This seems like some sort of setup issue.

**Comment by konfiot** [comment]
I have helm 2.9.1
Okay, I will join !

**Comment by tamalsaha** [comment]
Closing, since to recent activity. If you are still experiencing this, reopen.

**Comment by pojntfx** [comment]
In case someone is still running into this, run the following:

```bash
kubectl delete validatingwebhookconfiguration -l app=stash || true
kubectl delete mutatingwebhookconfiguration -l app=stash || true
kubectl delete apiservice -l app=stash
```

According to @tamalsaha, the problem appears to be the following:
> The problem is we install `ValidatingWebhook` using Helm hooks
> https://github.com/appscode/stash/blob/master/chart/stash/templates/validating-webhook.yaml#L11
> So, these are not deleted when the chart is uninstalled.

**Comment by tamalsaha** [comment]
@pojntfx , fyi, I have pushed an update to chart https://github.com/appscode/stash/pull/569 which will cleanup the webhook on delete in future.

**Comment by fdlk** [comment]
Running into this in stash 0.7 on minikube

**Comment by xamox** [comment]
> kubectl delete apiservice -l app=stash

Thanks, this worked for me as well.
