### ISSUE TITLE
Upgrade to restic 0.9.x

### ISSUE THREAD

**Issue by tamalsaha** [appscode/stash#520]

**Comment by hoatle** [comment]
I'm currently having a problem with the current restic version (0.8.3) which did not restore well on google cloud storage (stuck forever).

I tried with latest version of restic (0.9.4) and it works well.

Now I'm stuck with the latest version of stash (0.8.2) with the old version of restic (0.8.3).

Do we have any workaround/solution to specify to use a different version of restic for stash to recover/backup?

**Comment by hossainemruz** [comment]
@hoatle `restic 0.9.x` has changed backup process. It uses absolute path for backup and restore which is not backward compatible with `restic 0.8.x` which use relative path. So, we decided to stay with `restic 0.8.3`. However, in next version of Stash we are going to  upgrade `restic` to latest version(it won't be backward compatible).

Btw, did you found why `restic 0.8.3` stuck while restore?

**Comment by hoatle** [comment]
@hossainemruz I could not find out the reason why restic 0.8.3 was stuck when using google cloud storage, I tried the same with local backend, the backup and recovery works well. So I guess there could be something wrong specific to google cloud storage.

**Comment by hossainemruz** [comment]
@hoatle do you see any log in stash sidecar/backup job pod?

**Comment by hoatle** [comment]
@hossainemruz backup works well, only problem with recovery (restore).
the stash recovery job is stuck, running forever without any more debugging logs.

```
$ kubectl -n wordpress logs -f stash-recovery-wordpress-795rb 
I0214 12:45:19.120529       1 logs.go:19] FLAG: --alsologtostderr="false"
I0214 12:45:19.130035       1 logs.go:19] FLAG: --backoff-max-wait="0s"
I0214 12:45:19.130048       1 logs.go:19] FLAG: --bypass-validating-webhook-xray="false"
I0214 12:45:19.130055       1 logs.go:19] FLAG: --enable-analytics="true"
I0214 12:45:19.130062       1 logs.go:19] FLAG: --enable-status-subresource="true"
I0214 12:45:19.130069       1 logs.go:19] FLAG: --help="false"
I0214 12:45:19.130076       1 logs.go:19] FLAG: --kubeconfig=""
I0214 12:45:19.130084       1 logs.go:19] FLAG: --log-flush-frequency="5s"
I0214 12:45:19.130093       1 logs.go:19] FLAG: --log_backtrace_at=":0"
I0214 12:45:19.130101       1 logs.go:19] FLAG: --log_dir=""
I0214 12:45:19.130108       1 logs.go:19] FLAG: --logtostderr="true"
I0214 12:45:19.130114       1 logs.go:19] FLAG: --master=""
I0214 12:45:19.130121       1 logs.go:19] FLAG: --recovery-name="wordpress"
I0214 12:45:19.130128       1 logs.go:19] FLAG: --service-name="stash-operator"
I0214 12:45:19.130136       1 logs.go:19] FLAG: --stderrthreshold="0"
I0214 12:45:19.130143       1 logs.go:19] FLAG: --use-kubeapiserver-fqdn-for-aks="true"
I0214 12:45:19.130150       1 logs.go:19] FLAG: --v="3"
I0214 12:45:19.130157       1 logs.go:19] FLAG: --vmodule=""
W0214 12:45:20.517089       1 client_config.go:548] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
```

And I tried restic restore directly instead of stash.
- with restic 0.8.3 and gcs repo: restic restore was stuck.
```
# restic check
password is correct
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs

no errors were found
# restic restore a0513130 -t restore/
password is correct
restoring <Snapshot a0513130 of [/bitnami/wordpress] at 2019-02-14 04:20:10.890204694 +0000 UTC by @wp-app-wordpress> to restore/
```
- with restic 0.8.3, I tried to sync the gsc repo into the local file system and try restic restore from that local repo, it works then.

- with restic 0.9.4, restic restore directly from the gcs repo works.

**Comment by hoatle** [comment]
actually, it's not stuck but took a lot of time.
- It took about 28 seconds when I synced gcs repo into the local file system and then execute restic restore.

- It took about 23 minutes when I executed restic restore directly from the gcs repo.

I don't think this is acceptable when the restic repo is still very small (about 50MB in size).

```
root@6ed2a55b2030:/workspace# time restic restore a0513130 -r /tmp/ds-hoatle-iorad/k8s-local/deployment/wp-app-wordpress/ -t restore/
password is correct
restoring <Snapshot a0513130 of [/bitnami/wordpress] at 2019-02-14 04:20:10.890204694 +0000 UTC by @wp-app-wordpress> to restore/

real	0m28.839s
user	0m1.540s
sys	0m2.830s
root@6ed2a55b2030:/workspace# rm -rf restore/*
root@6ed2a55b2030:/workspace# time restic restore a0513130 -t restore/
password is correct
restoring <Snapshot a0513130 of [/bitnami/wordpress] at 2019-02-14 04:20:10.890204694 +0000 UTC by @wp-app-wordpress> to restore/

real	23m13.230s
user	0m7.560s
sys	0m25.380s
```

I guess I will need to recover manually as a workaround instead of using stash recovery until restic is upgraded.

**Comment by hossainemruz** [comment]
Fixed in https://github.com/appscode/stash/pull/675.

- Used `restic-0.8.3` for `v1alpha1` api.
- Used `restic-0.9.4` for `v1beta1` api.
