### ISSUE TITLE
[Request] Add backup details to "kubectl get" for stash objects on K8s 1.11

### ISSUE THREAD

**Issue by carlosedp** [appscode/stash#525]
Now on Kubernetes 1.11, it's possible to specify additional columns on `kubectl get` commands as stated [here](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.11.md#sig-api-machinery):

> In addition, users can now create multiple versions of CustomResourceDefinitions, but without any kind of automatic conversion, and CustomResourceDefinitions now allow specification of additional columns for kubectl get output via the spec.additionalPrinterColumns field.

Would be great to have the details on last backup, etc on the "get" command.

More details on https://github.com/kubernetes/kubernetes/pull/60991.

**Comment by tamalsaha** [comment]
Yes. My plan is we are going to cut another release for Stash that will push the fixes for 1.11 (eg status endpoint). After that we upgrade to client-go 1.8, drop support for k 1.8, use these new features, support arm build officially and psp enabled cluster.

**Comment by hossainemruz** [comment]
Additional column added. Available on master.
