### ISSUE TITLE
FR: Add possibility to change settings of Restic

### ISSUE THREAD

**Issue by nucleusv** [appscode/stash#545]
Hello, 

would be great to have possibility to change settings of Restic like this:

The number of concurrent connections to the Azure Blob Storage service can be set with the -o azure.connections=10. By default, at most five parallel connections are established.
https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html#microsoft-azure-blob-storage

**Comment by tamalsaha** [comment]
I agree. We should do this.

**Comment by tamalsaha** [comment]
- [ ] Add `Connections int `json:"connections,omitempty"`` to https://github.com/kmodules/objectstore-api/blob/master/api/v1/types.go for Azure, GCS, B2.
