### ISSUE TITLE
Cannot create deployment. Stash admission policy is preventing 

### ISSUE THREAD

**Issue by arjunsbabu** [appscode/stash#557]
HI Team ,
 We have just installed stash on an Ibm cloud private 2.1.0.3 EE kubernetes cluster. This is an HA env. We have installed using  the script in the appscode documentation directly.
But after it when im trying to create a deployment it not allowing me to do so. Please have a look at it

`root@gyfradgicpdevm01:~/workspace/stash# cat newdepploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dragon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arjun
  template:
    metadata:
      labels:
        app: arjun
    spec:
      containers:
      - name: stash-nginx-container
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: webdirectory
          mountPath: /usr/share/nginx/html
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
      volumes:
      - name: dragon
        persistentVolumeClaim:
          claimName:  dragon
root@gyfradgicpdevm01:~/workspace/stash# kubectl create -f newdepploy.yaml
Error from server (InternalError): error when creating "newdepploy.yaml": Internal error occurred: failed calling admission webhook "deployment.admission.stash.appscode.com": Unauthorized
root@gyfradgicpdevm01:~/workspace/stash#`

**Comment by tamalsaha** [comment]
I think you are facing https://github.com/kubernetes/kubernetes/pull/62649 issue. It was fixed in 1.10.2 

- https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.10.md#changelog-since-v1101
`Fixes the kubernetes.default.svc loopback service resolution to use a loopback configuration. (#62649, @liggitt)`

**Comment by arjunsbabu** [comment]
@tamalsaha got it..But just to let you know that we havent faced the issue in creating the deployment in another similar env. Not sure why there the k8 bug never applies.

**Comment by tamalsaha** [comment]
Closing out-dated issue. Please file a new issue with logs if you see this issue.
