### ISSUE TITLE
AdHoc/One-Time Backup

### ISSUE THREAD

**Issue by mitchellmaler** [appscode/stash#559]
Hello, 

Is there a way to create a one-time backup that is outside of the schedule. I have recurring backups but also want a way to have a backup run on demand.

Thanks

**Comment by JJSWAIN2018** [comment]
same things required here

**Comment by hossainemruz** [comment]
This is supported by `v1beta1` design and already doable in master.

`v1beta1` design discussion: https://github.com/appscode/stash/issues/648
