### ISSUE TITLE
Stash does not provide any validation for Restic's selector

### ISSUE THREAD

**Issue by arjunsbabu** [appscode/stash#579]
Hi Team,

I have multiple deployment which use the same PV , same mount point and same volume name. I have labelled one of the deployment and created a Restic to take backup. 

But the stash sidecar is getting added to all the deployments regardless it has the label that match Restic's selector. Later with the help of @hossainemruz we identified that the issue is a typo in the Restic's selector.
```
 selector:
   matchLabel:
```
I used above selector without an `s` ( plural ) in `matchLabels`. So the correct form should be
```
 selector:
   matchLabels:
```
So adding an 's' solved the issue. But this is not desired. Stash should give an validation error. Else peoples will not be aware about the issue and will get undesired state.

**Comment by tamalsaha** [comment]
This is not relevant in v1beta1 api. 

Also, given how CRD validation works, this can't be done using openapi-spec. https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/
