### ISSUE TITLE
Backup failed metrics not coming

### ISSUE THREAD

**Issue by arjunsbabu** [appscode/stash#595]
Hi TEam,

I have created a deployment and created a restic to take a backup every minute . We have configured an alert  rule in alert manager to get us an alert if backup fails . To check the same we have triggered a backup fail by manually deleting the secret. The backup got stopped but the push gateway is not sending any metrics to Prometheus .

![prometheus query](https://user-images.githubusercontent.com/29661675/46392138-d78a7100-c6fd-11e8-8b2d-1121582f0f56.jpg)
<img width="940" alt="stash dashboard2" src="https://user-images.githubusercontent.com/29661675/46392149-e96c1400-c6fd-11e8-90b5-e0d807574063.PNG">

**Comment by hossainemruz** [comment]
Stash `v1beta1` api sends failure metrics for both backup and recovery. It is added in #673.
