### ISSUE TITLE
Service name hardcoded in func PushgatewayURL, no metrics available

### ISSUE THREAD

**Issue by sebastien-prudhomme** [appscode/stash#596]
Hi, as the service name is hardcoded as "stash-operator" in the PushgatewayURL function, metrics are not available when using an Helm chart with a release name other than "stash-operator".

**Comment by hossainemruz** [comment]
ref: https://github.com/appscode/stash/blob/4506adea4cac4d6fb63d747c6a69e5c17d8c1727/pkg/util/kubernetes.go#L125
