### ISSUE TITLE
Support recovery without Repository crd

### ISSUE THREAD

**Issue by hossainemruz** [appscode/stash#605]
From stash 0.7.0, recovery need Repository crd. When someones cluster fail, he will lose Repository crd too. In this case user must create a Repository crd manually to recover. Creating Repository crd manually is not easy as it requires guessing repository name appropriately.

We should provide a way to recover without Repository crd.
cc: @farcaller

**Comment by tamalsaha** [comment]
Repository crd is now created by user. So, this issue is not relevant anymore.
