### ISSUE TITLE
Recovery task is not working

### ISSUE THREAD

**Issue by drazul** [appscode/stash#613]
Hi there,

I tried the tutorial example (https://github.com/appscode/stash/tree/master/docs/examples/tutorial) and recovery is not working.

I installed latest helm chart (stash-0.7.0) and tried different changes on the tutorial examples like don't use git repo as volume and use a hostpath and a volume claim, force all things will be deployed on same host and I always get the same error:

```
Status:
 Phase:  Failed
Events:
 Type     Reason              Age   From              Message
 ----     ------              ----  ----              -------
 Normal   RecoveryJobCreated  8s    stash-controller  Recovery job created: stash-recovery-stash-demo-2
 Warning  FailedRecovery      0s    stash-recovery    failed to recover FileGroup /source/data, reason: /safe/data/deployment/stash-demo
 Warning  FailedRecovery      0s    stash-recovery    Failed to complete recovery stash-demo-2, reason: /safe/data/deployment/stash-demo
```

Also I checked the stash-operator log and it says all is going fine

```
I1116 13:35:25.930652       1 jobs.go:50] Sync/Add/Update for Job stash-recovery-stash-demo-2                                                                          I1116 13:35:25.932512       1 serviceaccount.go:19] Creating ServiceAccount default/stash-recovery-stash-demo-2.
I1116 13:35:25.938209       1 rolebinding.go:19] Creating RoleBinding default/stash-recovery-stash-demo-2.                                                             I1116 13:35:25.987317       1 rolebinding.go:19] Creating RoleBinding default/stash-recovery-stash-demo-2:default:repo-reader.
I1116 13:35:26.007700       1 recoveries.go:186] [Recovery job created: stash-recovery-stash-demo-2]
I1116 13:35:26.007863       1 recovery.go:59] Patching Recovery default/stash-demo-2 with {"status":{"phase":"Running"}}.
I1116 13:35:26.010776       1 wrap.go:42] POST /apis/admission.stash.appscode.com/v1alpha1/recoveries: (853.776µs) 201 [[Go-http-client/2.0] 10.233.102.0:53514]
I1116 13:35:26.974133       1 jobs.go:50] Sync/Add/Update for Job stash-recovery-stash-demo-2
I1116 13:35:27.997144       1 wrap.go:42] GET /apis/admission.stash.appscode.com/v1alpha1: (1.234478ms) 200 [[hyperkube/v1.10.4 (linux/amd64) kubernetes/5ca598b/system
:serviceaccount:kube-system:generic-garbage-collector] 10.233.125.128:35104]
I1116 13:35:27.999620       1 wrap.go:42] GET /apis/repositories.stash.appscode.com/v1alpha1: (1.290689ms) 200 [[hyperkube/v1.10.4 (linux/amd64) kubernetes/5ca598b/sys
tem:serviceaccount:kube-system:generic-garbage-collector] 10.233.125.128:35104]
I1116 13:35:31.452653       1 wrap.go:42] GET /healthz: (1.23082ms) 200 [[kube-probe/1.10] 10.8.73.9:55594]
I1116 13:35:34.072535       1 wrap.go:42] POST /apis/admission.stash.appscode.com/v1alpha1/recoveries: (589.5µs) 201 [[Go-http-client/2.0] 10.233.102.0:53514]
I1116 13:35:34.078319       1 wrap.go:42] POST /apis/admission.stash.appscode.com/v1alpha1/recoveries: (633.117µs) 201 [[Go-http-client/2.0] 10.233.102.0:53514]
I1116 13:35:34.431400       1 jobs.go:50] Sync/Add/Update for Job stash-recovery-stash-demo-2                                                                          I1116 13:35:34.431415       1 jobs.go:53] Deleting succeeded job stash-recovery-stash-demo-2
I1116 13:35:34.436793       1 jobs.go:64] Deleted stash job: stash-recovery-stash-demo-2
```

Finally I add my modified files:
```
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: stash-demo
  name: stash-demo
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: stash-demo
      name: busybox
    spec:
      containers:
      - command:
        - sleep
        - "3600"
        image: busybox
        imagePullPolicy: IfNotPresent
        name: busybox
        volumeMounts:
        - mountPath: /source/data
          name: source-data
      restartPolicy: Always
      volumes:
      - name: source-data
        hostPath:
          path: /tmp/stash-demo
      nodeSelector:
        kubernetes.io/hostname: ipxx60

---
apiVersion: v1
data:
  RESTIC_PASSWORD: Y2hhbmdlaXQ=
kind: Secret
metadata:
  name: stash-demo
  namespace: default
type: Opaque

---
apiVersion: stash.appscode.com/v1alpha1
kind: Restic
metadata:
  name: stash-demo
  namespace: default
spec:
  selector:
    matchLabels:
      app: stash-demo
  fileGroups:
  - path: /source/data
    retentionPolicyName: 'keep-last-5'
  backend:
    local:
      mountPath: /safe/data
      hostPath:
        path: /data/stash-test/restic-repo
    storageSecretName: stash-demo
  schedule: '@every 1m'
  volumeMounts:
  - mountPath: /source/data
    name: source-data
  retentionPolicies:
  - name: 'keep-last-5'
    keepLast: 5
    prune: true
  nodeSelector:
    kubernetes.io/hostname: ipxx60
```

```
apiVersion: stash.appscode.com/v1alpha1
kind: Recovery
metadata:
  name: stash-demo-2
  namespace: default
spec:
  repository:
    name: deployment.stash-demo
    namespace: default
  paths:
  - /source/data
#  snapshot: deployment.stash-demo-0ee43a0a
  recoveredVolumes:
  - mountPath: /source/data
    hostPath:
      path: /data/stash-test/restic-restored
  nodeSelector:
    kubernetes.io/hostname: ipxx60
```

**Comment by lorenzomorandini** [comment]
Same problem, any news on this?

**Comment by hossainemruz** [comment]
@lorenzomorandini which stash version are you using? We have fixed this issue in https://github.com/appscode/stash/pull/620 and it is available in 0.8.x release.

**Comment by lorenzomorandini** [comment]
Version 0.7.3, I'm going to upgrade now. Can you please close the issue? I thought it still needed to be fixed

**Comment by lorenzomorandini** [comment]
Thank you btw

**Comment by hossainemruz** [comment]
Fixed in https://github.com/appscode/stash/pull/620. Fix available in Stash 0.8.x.

**Comment by lorenzomorandini** [comment]
**Deployment**
`kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  selector:
    matchLabels:
      app: gitlab
  replicas: 1
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce:11.5.1-ce.0
        volumeMounts:
        - mountPath: /var/opt/gitlab
          name: data
        - mountPath: /etc/gitlab/gitlab.rb
          subPath: gitlab.rb
          name: config
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: ssh
          containerPort: 22
        - name: registry
          containerPort: 4567
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: gitlab
      - name: config
        configMap:
          name: gitlab
`
**Restic**
`kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitlab-backup
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 10Gi
---
apiVersion: stash.appscode.com/v1alpha1
kind: Restic
metadata:
  name: gitlab-backup
  namespace: default
spec:
  selector:
    matchLabels:
      app: gitlab
  fileGroups:
  - path: /data
    retentionPolicyName: 'keep-last-3'
  backend:
    local:
      mountPath: /backup
      VolumeSource: backup
      # hostPath:
      #   path: /data/stash-test/restic-repo
    storageSecretName: stash-secret
  schedule: '0 1 * * *'
  volumeMounts:
  - mountPath: /data
    name: data
  # - mountPath: /backup
  #   name: backup
  retentionPolicies:
  - name: 'keep-last-3'
    keepLast: 3
    prune: true
  volumes:
    - name: data
      persistentVolumeClaim:
      claimName: gitlab
    - name: backup
      persistentVolumeClaim:
      claimName: gitlab-backup
`
**Recovery**
`apiVersion: stash.appscode.com/v1alpha1
kind: Recovery
metadata:
  name: gitlab
  namespace: default
spec:
  repository:
    name: deployment.gitlab
    namespace: default
  paths:
  - /data
  recoveredVolumes:
  - mountPath: /data
    persistentVolumeClaim:
      claimName: gitlab
`

**Comment by hossainemruz** [comment]
@lorenzomorandini your Restic specification doesn't seems to be right. If you want to backup in a PVC you have to specify `backend` section this way.

```yaml
backend:
  local:
    mountPath: /backup
    persistentVolumeClaim:
      claimName: gitlab-backup
  storageSecretName: stash-secret
```

**Comment by lorenzomorandini** [comment]
I'll try immediately and let you know, thank you.

**Comment by lorenzomorandini** [comment]
I confirm that was the problem, thank you.
