### ISSUE TITLE
Architecture questions

### ISSUE THREAD

**Issue by segator** [appscode/stash#635]
How exactly works the backup?
is a incremental backup system? 
how it detect no necesary to backup a file? (checksum, size+mtime?)
imagine you have milions of little files, but only 1 file of 1kb is changed, it will take long time to detect and sync the backup?

**Comment by hossainemruz** [comment]
@segator Stash uses [restic](https://restic.net/) for backup. `restic` follow a deduplication strategy for backup. Please read about how `restic` uses deduplication from [here](https://restic.readthedocs.io/en/stable/design.html?highlight=deduplication#backups-and-deduplication).

`restic` will read all target file and chunk it if it is larger than 512KB. Then, it will check if the chunk is already exist in backup. If exit it will not backup again.

So, if only 1 file of 1kb is changed it will be detected while reading the file. As, other files are not changed they will not be backed up again.

**Comment by segator** [comment]
thank you very much!!
