### ISSUE TITLE
Instance label in pushgateway is deprecated - Not use HostnameGroupingKey()

### ISSUE THREAD

**Issue by cyrilgt** [appscode/stash#670]
In file prometheus.go, you use the function HostnameGroupingKey() which is deprecated.
When K8s delete / create pods in same deployment, pod name change and old metrics are not deleted from pushgateway. 
Graphs and alerts show old success or failed backup.
Can you delete usage of this function ? I will try this code : 
```
var labels map[string]string
//labels := push.HostnameGroupingKey()
```
To enhance more metrics, you can view restic-robot, metrics are available in url /metrics for each "server" with size, number of files (processed, changed, added, ...). Stash + metrics of restic-robot will be awesome 👍

**Comment by hossainemruz** [comment]
@cyrilgt Thank you for your feedback. We will remove `HostnameGroupingKey()`. Btw, we are already working on improving Stash metrics. New metrics includes every metrics of restic-robot + more.

**Comment by tamalsaha** [comment]
https://github.com/prometheus/client_golang/blob/77e8f2ddcfed59ece3a8151879efb2304b5cbbcf/prometheus/push/deprecated.go#L161
