### ISSUE TITLE
Internal error occurred: failed calling webhook "deployment.admission.stash.appscode.com": the server is currently unable to handle the request

### ISSUE THREAD

**Issue by lorenzomorandini** [appscode/stash#692]
Hi,
sometimes stash doesn't allow us to create new deployments in our cluster (even if the deployment doesn't have anything to do with stash and backups).
The error is the following:
```
Error from server (InternalError): error when creating "manifest.yaml": Internal error occurred: failed calling webhook "deployment.admission.stash.appscode.com": the server is currently unable to handle the request
```

The commands from https://github.com/appscode/stash/issues/510 allow us to fix the problem but sometimes it reappears. I couldn't find a reason, it seems to appear randomly.

**Comment by hossainemruz** [comment]
@lorenzomorandini Stash uses mutating webhook that allow us to insert sidecar while creating a workload if there is Restic configured for this workload. Every workload(Deployment,StatefulSet,DaemonSet etc.) goes through this mutation webhook. So, if stash operator pod is unhealthy then you would become unable to create a workload. The workaround you have specified remove those webhooks.

**Comment by hossainemruz** [comment]
>The commands from #510 allow us to fix the problem but sometimes it reappears. I couldn't find a reason, it seems to appear randomly.

It shouldn't re-appear randomly. If you create those webhooks again and Stash operator pod is unhealthy only then the problem should re-appear.

Can you please share following information?
1. What version of Stash are you using?
2. What is your Kubernetes version?
3. What cloud provider are you using?
4. Log from stash operator pod.

**Comment by lorenzomorandini** [comment]
The stash operator was in error since he couldn't find the webhooks anymore, I uninstalled and installed stash, seems to be working now. I'm still not sure why it stopped working but if it happens again I'll report back.
1. Stash 0.8.3
2. Kubernetes 1.13.3
3. Self hosted

**Comment by tamalsaha** [comment]
xref: https://github.com/appscode/stash/issues/709

**Comment by tamalsaha** [comment]
This will be fixed by https://github.com/appscode/stash/issues/692

**Comment by tamalsaha** [comment]
Dup #709

**Comment by davidq2q** [comment]
I have similar problem but the namespace where stash was installed is stuck on deletion. This renders my cluster unresponsive.

**Comment by tamalsaha** [comment]
@davidq2q , a solution will be to apply this change https://github.com/stashed/stash/commit/36fdb9ae13152f8f72e2464e215ddd10b24f72ed . This will be part of next release. https://github.com/stashed/stash/pull/726
