### ISSUE TITLE
Cleanup old cache after backup

### ISSUE THREAD

**Issue by hossainemruz** [appscode/stash#703]
**Problem:**
We didn't cleanup old cache which lead to high memory usage.Ref: https://github.com/appscode/stash/issues/697

**Solution:**
Use `--cleanup-cache` flag with backup command. Ref: https://restic.readthedocs.io/en/stable/manual_rest.html?highlight=cache#usage-help

**Comment by pjaak** [comment]
thanks for looking into this!

**Comment by pjaak** [comment]
@hossainemruz do we have any update on this and if it will be added into a release?

**Comment by hossainemruz** [comment]
We are working on it. Wait for next release. This could be in 2nd week of April.

**Comment by tamalsaha** [comment]
This issue is unrelated from #697 . This one is about disk space used by /tmp folder for restic. This can be restricted to some user defined limit by setting the sizelimit field.

https://github.com/kubernetes/api/blob/kubernetes-1.13.0/core/v1/types.go#L602

**Comment by tamalsaha** [comment]
https://github.com/appscode/stash/pull/717
