### ISSUE TITLE
Register MutatingWebhookConfiguration for DeploymentConfig from chart

### ISSUE THREAD

**Issue by hossainemruz** [appscode/stash#727]
[mutatingwebhookconfiguration](https://github.com/appscode/stash/blob/4cab69a05108929e9510df09ae0232da4ddb9a87/hack/deploy/mutating-webhook.yaml#L105) for OpenShift `DeploymentConfig` is missing in chart.

**Comment by tamalsaha** [comment]
Fixed in https://github.com/appscode/stash/pull/725
