### ISSUE TITLE
Fix snapshot handling for new API

### ISSUE THREAD

**Issue by hossainemruz** [appscode/stash#738]
- Operator pod crash while get snapshot.
- For new design, there might be Repository crd but underlying restic repository might not be initialized yet. Don't return error in this case. Return empty snapshot list.
- Now stash uses both restic 0.8.3 and 0.9.4. Check snapshot handling works using only one of them.

**Comment by tamalsaha** [comment]
I think we should check if restic 0.9.4 can work with old repo or not. That will make it simple.
