### ISSUE TITLE
Send performance stats to Prometheus

### ISSUE THREAD

**Issue by tamalsaha** [appscode/stash#9]
- [ ] Duration of snapshot.
- [ ] Snapot success / fail
- [ ] Amount of data backed up

Given restic executions are short-lived jobs, we should use the Pushgateway:
https://prometheus.io/docs/instrumenting/pushing/

- Operator itself should expose metrics via `/metrics` port

**Comment by TamalSaha** [comment]
Run the https://github.com/prometheus/pushgateway as a sidecar to restik operator. Then configure Prometheus to scrape it.

**Comment by tamalsaha** [comment]
https://github.com/prometheus/client_golang/blob/master/prometheus/push/push_test.go
